<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.465" timestamp="2025-09-23T15:19:23.811231-07:00" hostname="MacBook-Air.local"><testcase classname="" name="unit.core.test_agent_integration" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/aq_home/1Projects/accessa/insurance_navigator/tests/unit/core/test_agent_integration.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../opt/anaconda3/lib/python3.9/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
../../../opt/anaconda3/lib/python3.9/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1030: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1007: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:986: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:680: in _load_unlocked
    ???
../../../opt/anaconda3/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/unit/core/test_agent_integration.py:18: in &lt;module&gt;
    from core.agent_integration import (
E   ModuleNotFoundError: No module named 'core.agent_integration'</error></testcase></testsuite></testsuites>